language: python
python:
  - "2.7"
  - "3.5"
  - "3.6-dev"
  - "pypy"
# Install script
install:
  - pip install .
  - pip install -r tests/requirements.txt
# command to run tests
script:
  - python setup.py test

